// <auto-generated />
using Business.WebAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace YedekParca.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250317123113_tt1")]
    partial class tt1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entity.ModelDef", b =>
                {
                    b.Property<int>("ModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModelID"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ModelID");

                    b.ToTable("ModelTanimlari");

                    b.HasData(
                        new
                        {
                            ModelID = 1,
                            ModelName = "JUMPER-3",
                            MotorName = "2.2 HDI",
                            Year = "06-"
                        },
                        new
                        {
                            ModelID = 2,
                            ModelName = "207/308/C4/MINI",
                            MotorName = "1.6 EP6",
                            Year = "07-"
                        },
                        new
                        {
                            ModelID = 3,
                            ModelName = "407/607",
                            MotorName = "BM",
                            Year = "97-"
                        },
                        new
                        {
                            ModelID = 4,
                            ModelName = "BOXER-3",
                            MotorName = "2.2 HDI",
                            Year = "06-"
                        });
                });

            modelBuilder.Entity("Data.Entity.StokDet", b =>
                {
                    b.Property<int>("StokID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StokID"));

                    b.Property<int>("ModelID")
                        .HasColumnType("integer");

                    b.Property<int>("StokAdn")
                        .HasColumnType("integer");

                    b.Property<int>("StokAnk")
                        .HasColumnType("integer");

                    b.Property<int>("StokErz")
                        .HasColumnType("integer");

                    b.Property<int>("StokIzm")
                        .HasColumnType("integer");

                    b.Property<int>("StokMRK")
                        .HasColumnType("integer");

                    b.Property<int>("YedekParcasId")
                        .HasColumnType("integer");

                    b.HasKey("StokID");

                    b.HasIndex("YedekParcasId");

                    b.ToTable("StokDetaylar");

                    b.HasData(
                        new
                        {
                            StokID = 1,
                            ModelID = 1,
                            StokAdn = 8,
                            StokAnk = 1,
                            StokErz = 1,
                            StokIzm = 1,
                            StokMRK = 0,
                            YedekParcasId = 1
                        },
                        new
                        {
                            StokID = 2,
                            ModelID = 2,
                            StokAdn = 13,
                            StokAnk = 1,
                            StokErz = 11,
                            StokIzm = 0,
                            StokMRK = 18,
                            YedekParcasId = 2
                        });
                });

            modelBuilder.Entity("Data.Entity.YedekParcaModel", b =>
                {
                    b.Property<int>("YedekParcasId")
                        .HasColumnType("integer");

                    b.Property<int>("ModelID")
                        .HasColumnType("integer");

                    b.HasKey("YedekParcasId", "ModelID");

                    b.HasIndex("ModelID");

                    b.ToTable("YedekParcaModel");
                });

            modelBuilder.Entity("Data.Entity.YedekParcas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("YedekParcalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaterialCode = "0249.E9",
                            MaterialName = "ÜST KAPAK CONTA",
                            Price = 1114.78f
                        },
                        new
                        {
                            Id = 2,
                            MaterialCode = "0249.F4",
                            MaterialName = "KÜLBÜTÖR KAPAK CONTASI",
                            Price = 837.47f
                        });
                });

            modelBuilder.Entity("Data.Entity.StokDet", b =>
                {
                    b.HasOne("Data.Entity.YedekParcas", "YedekParcas")
                        .WithMany("StokGuid")
                        .HasForeignKey("YedekParcasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YedekParcas");
                });

            modelBuilder.Entity("Data.Entity.YedekParcaModel", b =>
                {
                    b.HasOne("Data.Entity.ModelDef", "Model")
                        .WithMany("YedekParcaModelleri")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entity.YedekParcas", "YedekParcas")
                        .WithMany("YedekParcaModelleri")
                        .HasForeignKey("YedekParcasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("YedekParcas");
                });

            modelBuilder.Entity("Data.Entity.ModelDef", b =>
                {
                    b.Navigation("YedekParcaModelleri");
                });

            modelBuilder.Entity("Data.Entity.YedekParcas", b =>
                {
                    b.Navigation("StokGuid");

                    b.Navigation("YedekParcaModelleri");
                });
#pragma warning restore 612, 618
        }
    }
}
